/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter' at '17.12.15 03:01' with Gradle 2.9
 *
 * @author peter, @date 17.12.15 03:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
